name: _Mixin values

on:
  workflow_call:
    inputs:
      base:
        type: string
        required: true
      join:
        type: string
        required: true
    outputs:
      values:
        description: "Result"
        value: ${{ jobs.mixin.outputs.values }}

jobs:
  mixin:
    runs-on: ubuntu-latest
    steps:
      - id: mixin
        env:
          BASE: ${{ inputs.base }}
          JOIN: ${{ inputs.join }}
        run: |
          echo "${BASE}" | jq --argjson "mixin" "${JOIN}" '[.[] | $mixin[] as $y | . + $y]' > "result.json"
          echo values=$(cat "result.json") >> $GITHUB_OUTPUT
    outputs:
      values: ${{ steps.mixin.outputs.values }}
