name: Daily build

on:
  push:

jobs:
  determine_php_versions:
    uses: ./.github/workflows/_determine_php_versions.yml
    with:
      ignore_versions: '["8.1"]'
  generate_image_variants:
    needs: determine_php_versions
    uses: ./.github/workflows/__generate_image_variants.yml
    with:
      php_versions_json: ${{ needs.determine_php_versions.outputs.values }}
  build_base:
    needs: generate_image_variants
    uses: ./.github/workflows/___build_base.yml
    secrets: inherit
    strategy:
      max-parallel: 3
    with:
      image_variants: ${{ needs.generate_image_variants.outputs.values }}
      enable_minor: true
    