name: Daily build

on:
  push:

permissions:
  packages: write

jobs:
  determine_php_versions:
    uses: ./.github/workflows/_determine_php_versions.yml
    with:
      ignore_versions: '["8.1"]'
  generate_image_variants:
    needs: determine_php_versions
    uses: ./.github/workflows/__generate_image_variants.yml
    with:
      php_versions_json: ${{ needs.determine_php_versions.outputs.values }}
  # build_base:
  #   needs: generate_image_variants
  #   uses: ./.github/workflows/___build_base.yml
  #   with:
  #     image_variants: ${{ needs.generate_image_variants.outputs.values }}
  #     enable_minor: true
  determine_types:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 1
      - name: Determine types
        id: determine_types
        run: |
          echo values=$(ls "types" | jq -R -s -c 'split("\n")[:-1] | map({"types": .})') >> $GITHUB_OUTPUT
    outputs:
      values: ${{ steps.determine_types.outputs.values }}
  mixin_types:
    needs: ["generate_image_variants", "determine_types"]
    uses: ./.github/workflows/_mixin_values.yml
    with:
      base: ${{ needs.generate_image_variants.outputs.values }}
      join: ${{ needs.determine_types.outputs.values }}
  build_variants:
    needs: mixin_types
    uses: ./.github/workflows/___build_variants.yml
    with:
      matrix_include: ${{ needs.mixin_types.outputs.values }}
      enable_minor: true
